#!/usr/bin/env bash
# Generates nix/deps.nix from nimble.lock using nix-prefetch-git.
# Usage: ./tools/gen-nix-deps.sh [nimble.lock] [nix/deps.nix]
#
# Each generated fetchgit block also records two observed facts about
# the upstream repository, on a comment line ("# observed: ..."):
#
#   tags=0|1      The repository has at least one git tag. Observed
#                 with `git ls-remote --tags <url>` — the same command
#                 Nimble runs to enumerate versions (getTagsListRemote,
#                 src/nimblepkg/download.nim:208, nimble v0.24.1).
#   registry=0|1  The lock name is in the official Nimble registry
#                 (packages.json, the source Nimble resolves names
#                 through: src/nimblepkg/config.nim:25, nimble v0.24.1)
#                 AND the registry URL equals the lock URL.
#
# scripts/gen_requires.py reads these columns to derive the requirement
# form for each package. The observation and the content hash come from
# the same visit and are written in the same pass, so the two cannot
# describe different states of the upstream world.
set -euo pipefail

usage() {
  cat <<EOF
Usage:
  $0 <nimble.lock> <output.nix>

Example:
  $0 nimble.lock nix/deps.nix
EOF
}

if [[ "${1:-}" == "-h" || "${1:-}" == "--help" ]]; then
  usage; exit 0
fi

if [[ $# -ne 2 ]]; then
  usage; exit 1
fi

LOCKFILE="$1"
OUTFILE="$2"

command -v jq             >/dev/null || { echo "error: jq required";             exit 1; }
command -v nix-prefetch-git >/dev/null || { echo "error: nix-prefetch-git required"; exit 1; }

if [[ ! -f "$LOCKFILE" ]]; then
  echo "[!] $LOCKFILE not found"
  echo "[*] Generating $LOCKFILE via 'nimble lock'"
  nimble lock
fi

# Lowercase, then remove one trailing "/" and one trailing ".git".
norm_url() {
  local u="${1,,}"
  u="${u%/}"
  u="${u%.git}"
  echo "$u"
}

# One registry fetch per run. The mirrors are the ones Nimble itself
# uses (src/nimblepkg/config.nim:25, nimble v0.24.1).
REG_JSON=$(mktemp)
reg_fetched=0
for reg_url in \
  "https://raw.githubusercontent.com/nim-lang/packages/master/packages.json" \
  "https://packages.nim-lang.org/packages.json"; do
  if curl -fsSL "$reg_url" -o "$REG_JSON"; then
    reg_fetched=1
    echo "[*] Registry fetched from $reg_url"
    break
  fi
done
if [[ "$reg_fetched" -ne 1 ]]; then
  echo "error: could not fetch the Nimble registry packages.json"
  rm -f "$REG_JSON"
  exit 1
fi

echo "[*] Generating $OUTFILE from $LOCKFILE"
mkdir -p "$(dirname "$OUTFILE")"

TMPFILE=$(mktemp)
trap 'rm -f "$TMPFILE" "$REG_JSON"' EXIT

# This block writes the header of the output file.
cat > "$TMPFILE" <<'EOF'
# This file is AUTOGENERATED — do not edit it manually.
# Regenerate with: ./tools/gen-nix-deps.sh nimble.lock nix/deps.nix
#
# Each entry has three sources:
# - url and rev come from nimble.lock.
# - sha256 comes from nix-prefetch-git.
# - The "# observed:" line records two facts about the upstream
#   repository at generation time: does it have git tags, and is it
#   in the Nimble registry under this name with this URL.
#   scripts/gen_requires.py reads these lines; nix ignores them.
{ pkgs }:

{
EOF

jq -c '
  .packages
  | to_entries[]
  | select(.value.downloadMethod == "git")
  | select(.key != "nim" and .key != "nimble")
' "$LOCKFILE" | while read -r entry; do
  name=$(jq -r '.key'              <<<"$entry")
  url=$(jq -r  '.value.url'        <<<"$entry")
  rev=$(jq -r  '.value.vcsRevision' <<<"$entry")

  echo "  [*] Prefetching $name @ $rev"

  sha=$(nix-prefetch-git \
    --url "$url" \
    --rev "$rev" \
    --fetch-submodules \
    | jq -r '.sha256')

  # Observe: does the repository have git tags? Only lines that name
  # refs/tags/ count: stderr is discarded, so a redirect warning from
  # a renamed repository cannot count as a tag. A failed command is a
  # network or access problem and stops the generation.
  if ! tag_list=$(git ls-remote --tags "$url" 2>/dev/null); then
    echo "error: git ls-remote --tags failed for $url"
    exit 1
  fi
  if grep -q "refs/tags/" <<<"$tag_list"; then tags=1; else tags=0; fi

  # Observe: is the lock name in the registry, with the lock URL?
  # Alias entries are followed one level, as Nimble does.
  reg_pkg_url=$(jq -r --arg n "$name" '
    def find($nm): [.[] | select((.name | ascii_downcase) == ($nm | ascii_downcase))][0];
    find($n) as $e
    | if $e == null then ""
      elif ($e | has("alias")) then (find($e.alias).url // "")
      else ($e.url // "")
      end
  ' "$REG_JSON")
  registry=0
  if [[ -n "$reg_pkg_url" && "$(norm_url "$reg_pkg_url")" == "$(norm_url "$url")" ]]; then
    registry=1
  fi

  cat >> "$TMPFILE" <<EOF
  ${name} = pkgs.fetchgit {
    url = "${url}";
    rev = "${rev}";
    sha256 = "${sha}";
    fetchSubmodules = true;
    # observed: tags=${tags} registry=${registry}
  };

EOF
done

cat >> "$TMPFILE" <<'EOF'
}
EOF

mv "$TMPFILE" "$OUTFILE"
echo "[✓] Wrote $OUTFILE"
